// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sssemrcdmkfcsfgcrwzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzc2VtcmNkbWtmY3NmZ2Nyd3pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4OTQxNDcsImV4cCI6MjA2NDQ3MDE0N30.KQADAoMhz99qs8sMS1JVFMUXbo3-qIsnXKVbwWcurDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);